# Generated by Django 3.2.7 on 2021-10-19 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.CharField(max_length=2)),
                ('celular', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('perfil', models.TextField()),
                ('experiencia_laboral', models.TextField()),
                ('formacion_academica', models.TextField()),
                ('objetivos', models.TextField()),
            ],
        ),
    ]
