# Generated by Django 3.2.7 on 2021-10-22 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0002_rename_post_curriculum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curriculum',
            old_name='formacion_academica',
            new_name='conocimientos',
        ),
        migrations.AddField(
            model_name='curriculum',
            name='año_en_curso',
            field=models.CharField(choices=[('1er año', '1er año'), ('2do año', '2do año'), ('3er año', '3er año'), ('4to año', '4to año'), ('5to año', '5to año'), ('6to año', '6to año'), ('7mo año', '7mo año'), ('8vo año', '8vo año'), ('9no año', '9no año'), ('10mo año', '10mo año')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='formacion_académica',
            field=models.CharField(choices=[('Primario incompleto', 'Primario incompleto'), ('Primario en curso', 'Primario en curso'), ('Primario terminado', 'Primario terminado'), ('Secundario incompleto', 'Secundario incompleto'), ('Secundario en curso', 'Secundario en curso'), ('Secundario terminado', 'Secundario terminado'), ('Terciario incompleto', 'Terciario incompleto'), ('Terciario en curso', 'Terciario en curso'), ('Terciario terminado', 'Terciario terminado'), ('Universitario incompleto', 'Universitario incompleto'), ('Universitario en curso', 'Universitario en curso'), ('Universitario terminado', 'Universitario terminado')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='foto',
            field=models.ImageField(null=True, upload_to='fotos'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='institucion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='edad',
            field=models.CharField(max_length=10),
        ),
    ]
