# Generated by Django 3.2.7 on 2021-10-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0003_auto_20211021_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='hobbies',
            field=models.TextField(null=True),
        ),
    ]
